### ISSUE TITLE
monthly-upsell class can cause conflicts with recurrpay-N

### ISSUE THREAD

**Issue by bryancasler** [4site-interactive-studios/engrid-template#83]
**Note, this might just need a call to the new Function Fernando discovered and created to trigger all EN conditional logic**

Clicking a monthly upsell pseudo checkbox (https://d.pr/i/T1iD8W) causes the giving amount to update, but doesn't trigger the other function that should hide all element with recurrpay-N. However, clicking "Monthly" giving frequency on the top of the page, does trigger the "recurrpay-N" behavior.

```
<!-- Custom Checkbox using the same markup as Engaging Networks -->
<div class="en__field en__field--checkbox en__field--000000 en__field--monthly_upsell_checkbox pseudo-en-field recurrpay-N"><!--<label class="en__field__label en__field__label--positionabove" style=""></label>-->
<div class="en__field__element en__field__element--checkbox">
<div class="en__field__item"><input class="en__field__input en__field__input--checkbox monthly-upsell" id="en__field_supporter_monthly_upsell_checkbox" name="supporter.monthly_upsell_checkbox" type="checkbox" value="Y" /> <label class="en__field__label en__field__label--item" for="en__field_supporter_monthly_upsell_checkbox"><span class="highlight">Make this a monthly recurring gift!</span> Recurring gifts help us act faster on urgent issues.</label></div>
</div>
</div>
```

**Comment by fernanDOTdo** [comment]
It's done on this commit: https://github.com/4site-interactive-studios/engrid-scripts/commit/a376d6171b40b62c0b1e648e115b2794a368c526
